---
- hosts: all
  gather_facts: true
  tasks:
    - name: Dump All hostvars for this instance
      debug:
        var: hostvars[inventory_hostname]

    - name: Dump morpheus variable for this instance
      debug:
        var: hostvars[inventory_hostname]['morpheus']

    - name: Dump morpheus variable raw
      debug:
        var: morpheus
