---
- hosts: all
  gather_facts: true
  tasks:
    - debug:
        msg: "{{ item }}"
      loop:
        - "IPv4: {{ ansible_all_ipv4_addresses }}"
        - "Distro: {{ ansible_distribution }}"
        - "Distro Version: {{ ansible_distribution_version }}"
        - "FDQN: {{ ansible_fqdn }}"
        - "This is an extra variable:  {{ extra_var_example }}"
        - "Metadata: {{ morpheus.instance.metadata }}"
        - "All Morpheus vars: {{ morpheus }}"
