---
- hosts: all
  gather_facts: true
  tasks:
    - debug:
        msg: "{{ item }}"
      loop:
        - "{{ ansible_all_ipv4_addresses }}"
        - "{{ ansible_distribution }}"
        - "{{ ansible_distribution_version }}"
        - "{{ ansible_fqdn }}"
        - "This is an extra variable:  {{ extra_var_example }}"
