- hosts: all
  tasks:
    - name: ls on remote
      shell: ls -la
      register: remote_out
    
    - name: ls on local
      local_action: shell ansible-config dump
      become: no
      register: local_out

    - debug:
        var: remote_out
    
    - debug:
        var: local_out
